### ISSUE TITLE
How to stop auto-redirect on date-time select

### ISSUE THREAD

**Issue by dklinger** [bnw/firefly-iii-fints-importer#102]
Hi,
how can I stop the auto-redirect on the date-time select page?
![image](https://github.com/bnw/firefly-iii-fints-importer/assets/2249766/706994d2-d886-4b7a-9310-8574bf83f2c9)

**Comment by JuliusFreudenberger** [comment]
The screenshot you posted seems to already state the solution. In the configuration file the date range has already been set leading to the auto-redirect. Did you try removing the date range in the configuration file you use?

**Comment by dklinger** [comment]
Thanks for the reply. Yes, and I got an error that the date is required.
What is the correct way of removing the date? To remove the property or to pass an empty string?

**Comment by JuliusFreudenberger** [comment]
Disclaimer, I'm not the maintainer, just a happy user with this app. I'm even not a PHP developer.

As far as I understand the code, [here](https://github.com/bnw/firefly-iii-fints-importer/blob/f046ccbf588961000ac7e8e53671581f69e29d5e/app/CollectData.php#L53-L54) the configuration is loaded. It then is later used [here](https://github.com/bnw/firefly-iii-fints-importer/blob/f046ccbf588961000ac7e8e53671581f69e29d5e/app/ChooseAccount.php#L72-L73) and directly passed to DateTime() - thats also stated in the [example configuration file](https://github.com/bnw/firefly-iii-fints-importer/blob/f046ccbf588961000ac7e8e53671581f69e29d5e/data/configurations/example.json#L16).
The problem is the following: The decision to skip this page is made solely based on the presence of the configuration parameters `from` and `to` [here](https://github.com/bnw/firefly-iii-fints-importer/blob/f046ccbf588961000ac7e8e53671581f69e29d5e/app/ChooseAccount.php#L77).
So your case is not covered yet leading to the behavior you experience. 

I got around it by changing the date fast enough in the limited time frame the page is shown.
I think a better decision making should be implemented here.
IMO the easiest solution is to add the date range to the check if the page should be skipped.
However, as I'm not a PHP developer (I could read it just enough though, that's how I came up with my analysis), I don't think I can accomplish this in a good way.

**Comment by bnw** [comment]
Hi,
sorry for the late reply and thanks for your investigations @JuliusFreudenberger.  
You can prevent the automatic date skipping by setting the `from` and `to` attributes to `null`.  
I have extended the example configuration to document this.
Hope this helps :)

**Comment by dklinger** [comment]
@bnw Thanks. That's what I was searching for.
