### ISSUE TITLE
GLS Bank import failed | Ungültige Auftragsnachricht

### ISSUE THREAD

**Issue by langfingaz** [bnw/firefly-iii-fints-importer#111]
Hi, many thanks for developing this importer!

I tried to import data from the GLS Bank using the following values:
* URL: https://hbci-pintan.gad.de/cgi-bin/hbciservlet (Returned by https://github.com/dr-duplo/python-fints-url)
* BLZ: 43060967 (Source: https://www.gls.de/privatkunden/faq/ueber-die-gls-bank-und-ihre-arbeit/wie-lauten-blz-und-bic-der-gls-bank/)
* 2FA: 944

I ran the importer with Docker Compose and the latest image (benkl/firefly-iii-fints-importer, 2a21fad54eaf)

I got this error message:

```
Fatal error: Uncaught Fhp\Protocol\ServerException: FinTS errors: 9050 (global): Die Nachricht enthält Fehler. 9800 (global): Dialog abgebrochen 9110 (global): Ungültige Auftragsnachricht: Unbekannter Aufbau. in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php:170 Stack trace: #0 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(963): Fhp\Protocol\ServerException::detectAndThrowErrors(Object(Fhp\Protocol\Message), Object(Fhp\Protocol\Message)) #1 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(307): Fhp\FinTs->sendMessage(Object(Fhp\Protocol\Message)) #2 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(832): Fhp\FinTs->execute(Object(Fhp\Protocol\DialogInitialization)) #3 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(705): Fhp\FinTs->executeWeakDialogInitialization(NULL) #4 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(674): Fhp\FinTs->ensureSynchronized() #5 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(532): Fhp\FinTs->ensureTanModesAvailable() #6 /app/FinTsFactory.php(55): Fhp\FinTs->getTanModes() #7 /app/FinTsFactory.php(30): App\FinTsFactory::get_tan_mode(Object(Fhp\FinTs), Object(Symfony\Component\HttpFoundation\Session\Session)) #8 /app/Choose2FADevice.php(25): App\FinTsFactory::create_from_session(Object(Symfony\Component\HttpFoundation\Session\Session)) #9 /app/index.php(55): App\StepFunction\Choose2FADevice() #10 {main} thrown in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php on line 170
```

**Comment by langfingaz** [comment]
I think that the problem was my username with 32 characters ...

The FinTS API allows only usernames with at most 30 characters. When creating an online banking account at the GLS Bank, one can create a username with 32 characters and when changing it later while logged in, one can even use 35 characters. I reported this to the GLS Bank.

Once I tested to use the Firefly importer with a shorter username I will close this issue.

**Comment by krischan81** [comment]
Unfortunately, it's not working for me. My username is less than 32 chars, so that can't be the issue

`Fatal error: Uncaught Fhp\Protocol\ServerException: FinTS errors: 9050 (global): Die Nachricht enthält Fehler. 9800 (global): Dialog abgebrochen 9120 (global): Die Nachricht hat nicht die erwartete Nachrichtennummer. in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php:170 Stack trace: #0 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(963): Fhp\Protocol\ServerException::detectAndThrowErrors(Object(Fhp\Protocol\Message), Object(Fhp\Protocol\Message)) #1 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(307): Fhp\FinTs->sendMessage(Object(Fhp\Protocol\Message)) #2 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(263): Fhp\FinTs->execute(Object(Fhp\Protocol\DialogInitialization)) #3 /app/Login.php(23): Fhp\FinTs->login() #4 /app/TanHandler.php(41): App\StepFunction\{closure}() #5 /app/TanHandler.php(31): App\TanHandler->create_or_continue_action() #6 /app/Login.php(21): App\TanHandler->__construct(Object(Closure), 'login-action', Object(Symfony\Component\HttpFoundation\Session\Session), Object(Twig\Environment), Object(Fhp\FinTs), Object(App\Step), Object(Symfony\Component\HttpFoundation\Request)) #7 /app/index.php(59): App\StepFunction\Login() #8 {main} thrown in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php on line 170`
