### ISSUE TITLE
Support non-IBAN account numbers

### ISSUE THREAD

**Issue by rytilahti** [bnw/firefly-iii-fints-importer#6]
This would allow importing older, pre-IBAN times, transactions. I don't know if firefly-iii can do automatic conversion to IBAN (probably not), so besides saving the information as it is it could be useful to convert the old information to IBAN?

Error during import: `This is not a valid IBAN.`

The keys from debug output:
```
 [bankCode:protected] => XXXXXXXX 
 [accountNumber:protected] => YYYYYYYYYY
```

Looks also that like my bank, DKB, is still today using the old bankCode & accountNumber for some (internal) transactions.

**Comment by bnw** [comment]
Somehow, for the automatic construction of the IBAN from a bank code and an account number, I could not find any readily available php library (within 15min of googleing). Maybe there is actually more to it than just concatenating the two and calculating a checksum?
If somebody points me to a library that does it, i'll hapily incorporate it.

I've added a check so that the account number will only be used as iban if it is indeed a valid iban. That should allow these transactions to be imported. On the firefly side, the account will be identified by name, instead of IBAN.

**Comment by rytilahti** [comment]
Thanks, your recent fixes allowed importing all the available transactions from my bank! :tada: 

Looks like converting an arbitrary bank & account numbers to IBAN is not as straight-forward as I thought (the format is country specific, https://en.wikipedia.org/wiki/International_Bank_Account_Number#IBAN_formats_by_country).
